version: '3.3'

networks:
  rabbit-network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - rabbit-network
    ports:
      - 8080:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  producer:
    build: ./producer
    networks:
      - rabbit-network
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 4
    environment:
      PORT: 8080
      UV_THREADPOOL_SIZE: 128
      AMQP_URI: amqp://admin:admin@rabbitmq
      CHANNEL_NAME: TestChannel
      QUEUE_NAME: TestQueue
    links:
      - rabbitmq
  consumer:
    build: ./consumer
    networks:
      - rabbit-network
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 4
    environment:
      AMQP_URI: amqp://admin:admin@rabbitmq
      CHANNEL_NAME: TestChannel
      QUEUE_NAME: TestQueue
    links:
      - rabbitmq
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - rabbit-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - producer
      - consumer
    ports:
      - "4000:4000"
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1